"""add food catalog and allergen traceability

Revision ID: 0f209686ddbd
Revises: 786a3450d5e4
Create Date: 2026-08-19 11:58:27.875949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f209686ddbd'
down_revision: Union[str, Sequence[str], None] = '786a3450d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('display_name_ar', sa.String(length=255), nullable=False),
    sa.Column('display_name_en', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergens_code'), 'allergens', ['code'], unique=True)
    op.create_table('catalog_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('license_url', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_sources_code'), 'catalog_sources', ['code'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('display_name_ar', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_canonical_name'), 'ingredients', ['canonical_name'], unique=True)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('food_kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('food_group', sa.String(length=100), nullable=True),
    sa.Column('meal_tags', sa.JSON(), nullable=False),
    sa.Column('basis_grams', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("data_quality IN ('verified', 'estimated')", name='ck_food_data_quality_allowed'),
    sa.CheckConstraint("food_kind IN ('food', 'recipe')", name='ck_food_kind_allowed'),
    sa.CheckConstraint('basis_grams > 0', name='ck_food_basis_grams_positive'),
    sa.ForeignKeyConstraint(['source_id'], ['catalog_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_food_source_external_id')
    )
    op.create_index(op.f('ix_foods_display_name'), 'foods', ['display_name'], unique=False)
    op.create_index(op.f('ix_foods_is_active'), 'foods', ['is_active'], unique=False)
    op.create_index(op.f('ix_foods_source_id'), 'foods', ['source_id'], unique=False)
    op.create_table('ingredient_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('present', 'absent', 'unknown')", name='ck_ingredient_allergen_status_allowed'),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['catalog_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'allergen_id', name='uq_ingredient_allergen')
    )
    op.create_index(op.f('ix_ingredient_allergens_allergen_id'), 'ingredient_allergens', ['allergen_id'], unique=False)
    op.create_table('food_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('present', 'absent', 'unknown')", name='ck_food_allergen_status_allowed'),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['catalog_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'allergen_id', name='uq_food_allergen')
    )
    op.create_index(op.f('ix_food_allergens_allergen_id'), 'food_allergens', ['allergen_id'], unique=False)
    op.create_index(op.f('ix_food_allergens_food_id'), 'food_allergens', ['food_id'], unique=False)
    op.create_table('food_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('amount_g', sa.Float(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.CheckConstraint('amount_g IS NULL OR amount_g >= 0', name='ck_food_ingredient_amount_nonnegative'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'ingredient_id', name='uq_food_ingredient')
    )
    op.create_index(op.f('ix_food_ingredients_food_id'), 'food_ingredients', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_ingredients_ingredient_id'), 'food_ingredients', ['ingredient_id'], unique=False)
    op.create_table('food_nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_code', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('basis_grams', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.CheckConstraint("data_quality IN ('verified', 'estimated')", name='ck_food_nutrient_data_quality_allowed'),
    sa.CheckConstraint('amount >= 0', name='ck_food_nutrient_amount_nonnegative'),
    sa.CheckConstraint('basis_grams > 0', name='ck_food_nutrient_basis_grams_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'nutrient_code', name='uq_food_nutrient')
    )
    op.create_index(op.f('ix_food_nutrients_food_id'), 'food_nutrients', ['food_id'], unique=False)
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.CheckConstraint('grams > 0', name='ck_food_portion_grams_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'label', name='uq_food_portion_label')
    )
    op.create_index(op.f('ix_food_portions_food_id'), 'food_portions', ['food_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_portions_food_id'), table_name='food_portions')
    op.drop_table('food_portions')
    op.drop_index(op.f('ix_food_nutrients_food_id'), table_name='food_nutrients')
    op.drop_table('food_nutrients')
    op.drop_index(op.f('ix_food_ingredients_ingredient_id'), table_name='food_ingredients')
    op.drop_index(op.f('ix_food_ingredients_food_id'), table_name='food_ingredients')
    op.drop_table('food_ingredients')
    op.drop_index(op.f('ix_food_allergens_food_id'), table_name='food_allergens')
    op.drop_index(op.f('ix_food_allergens_allergen_id'), table_name='food_allergens')
    op.drop_table('food_allergens')
    op.drop_index(op.f('ix_ingredient_allergens_allergen_id'), table_name='ingredient_allergens')
    op.drop_table('ingredient_allergens')
    op.drop_index(op.f('ix_foods_source_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_is_active'), table_name='foods')
    op.drop_index(op.f('ix_foods_display_name'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_ingredients_canonical_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_catalog_sources_code'), table_name='catalog_sources')
    op.drop_table('catalog_sources')
    op.drop_index(op.f('ix_allergens_code'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
