"""add explicit user food feedback

Revision ID: a298050d9bcf
Revises: 0f209686ddbd
Create Date: 2026-08-19 18:00:57.403527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a298050d9bcf'
down_revision: Union[str, Sequence[str], None] = '0f209686ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_food_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('like', 'dislike', 'save', 'not_interested')", name='ck_user_food_feedback_event_type_allowed'),
    sa.CheckConstraint('score IN (-1.0, 0.5, 1.0)', name='ck_user_food_feedback_score_allowed'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_id', name='uq_user_food_feedback')
    )
    op.create_index(op.f('ix_user_food_feedback_food_id'), 'user_food_feedback', ['food_id'], unique=False)
    op.create_index(op.f('ix_user_food_feedback_user_id'), 'user_food_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_food_feedback_user_id'), table_name='user_food_feedback')
    op.drop_index(op.f('ix_user_food_feedback_food_id'), table_name='user_food_feedback')
    op.drop_table('user_food_feedback')
    # ### end Alembic commands ###
